local T = dofile(TESTS_DIR .. '/helpers.lua')
local comments = require('config.diff_review.comments')

T.describe('diff_review/comments.lua', function()
  T.it('adds a comment and normalizes new_line to side/line', function()
    comments.reset()
    local c, err = comments.add({ file = 'a.txt', new_line = 10, body = 'hello', author = 'claude' })
    T.ok(c, err)
    T.eq(c.side, 'new')
    T.eq(c.line, 10)
    T.eq(c.author, 'claude')
    T.eq(c.parent_id, vim.NIL)
    T.eq(comments.version(), 1)
  end)

  T.it('stores an optional line_end for range comments and rejects bad ranges', function()
    comments.reset()
    local c = comments.add({ file = 'a.lua', new_line = 10, line_end = 14, body = 'range', author = 'claude' })
    T.eq(c.line, 10)
    T.eq(c.line_end, 14)
    -- replies inherit the range
    local r = comments.reply({ parent_id = c.id, body = 'ok' })
    T.eq(r.line_end, 14)
    -- line_end < line is rejected
    T.ok(select(1, comments.add({ file = 'a', new_line = 10, line_end = 5, body = 'x' })) == nil)
    -- plain single-line comment has no line_end
    local single = comments.add({ file = 'a', new_line = 2, body = 'y' })
    T.eq(single.line_end, vim.NIL)
  end)

  T.it('normalizes old_line to the old side', function()
    comments.reset()
    local c = comments.add({ file = 'a.txt', old_line = 4, body = 'x' })
    T.eq(c.side, 'old')
    T.eq(c.line, 4)
    T.eq(c.author, 'human')
  end)

  T.it('rejects missing file / body / target', function()
    comments.reset()
    T.ok(select(1, comments.add({ new_line = 1, body = 'x' })) == nil, 'missing file rejected')
    T.ok(select(1, comments.add({ file = 'a', new_line = 1 })) == nil, 'missing body rejected')
    T.ok(select(1, comments.add({ file = 'a', body = 'x' })) == nil, 'missing target rejected')
    T.ok(select(1, comments.add({ file = 'a', body = 'x', new_line = 0 })) == nil, 'zero line rejected')
    T.eq(comments.version(), 0)
  end)

  T.it('replies inherit the parent target and bump version', function()
    comments.reset()
    local top = comments.add({ file = 'a.txt', new_line = 10, body = 'root' })
    local r, err = comments.reply({ parent_id = top.id, body = 'reply', author = 'claude' })
    T.ok(r, err)
    T.eq(r.parent_id, top.id)
    T.eq(r.file, 'a.txt')
    T.eq(r.side, 'new')
    T.eq(r.line, 10)
    -- reply to a reply flattens onto the same root thread
    local r2 = comments.reply({ parent_id = r.id, body = 'nested' })
    T.eq(r2.parent_id, top.id)
  end)

  T.it('rejects reply to a missing parent', function()
    comments.reset()
    T.ok(select(1, comments.reply({ parent_id = 'nope', body = 'x' })) == nil)
  end)

  T.it('groups threads with replies', function()
    comments.reset()
    local top = comments.add({ file = 'a.txt', new_line = 1, body = 'root' })
    comments.reply({ parent_id = top.id, body = 'r1' })
    comments.reply({ parent_id = top.id, body = 'r2' })
    comments.add({ file = 'a.txt', new_line = 2, body = 'other' })
    local threads = comments.threads()
    T.eq(#threads, 2)
    T.eq(#threads[1].replies, 2)
    T.eq(#threads[2].replies, 0)
  end)

  T.it('filters list/threads by file and author', function()
    comments.reset()
    comments.add({ file = 'a.txt', new_line = 1, body = 'a', author = 'human' })
    comments.add({ file = 'b.txt', new_line = 1, body = 'b', author = 'claude' })
    T.eq(#comments.list({ file = 'a.txt' }), 1)
    T.eq(#comments.list({ author = 'claude' }), 1)
    T.eq(#comments.threads({ file = 'b.txt' }), 1)
  end)

  T.it('tags comments with a view bucket (default uncommitted) and filters by it', function()
    comments.reset()
    local a = comments.add({ file = 'a.txt', new_line = 1, body = 'on uncommitted' })
    local b = comments.add({ file = 'a.txt', new_line = 2, body = 'on committed', view = 'committed' })
    T.eq(a.view, 'uncommitted')  -- 省略時は uncommitted
    T.eq(b.view, 'committed')
    -- 未知の view と旧名 'all' は uncommitted に丸める
    local c = comments.add({ file = 'a.txt', new_line = 3, body = 'weird', view = 'bogus' })
    T.eq(c.view, 'uncommitted')
    local legacy = comments.add({ file = 'a.txt', new_line = 4, body = 'legacy', view = 'all' })
    T.eq(legacy.view, 'uncommitted')
    -- 返信は親の view を継承する
    local r = comments.reply({ parent_id = b.id, body = 'reply on committed' })
    T.eq(r.view, 'committed')
    -- view フィルタでバケットごとに引ける
    T.eq(#comments.list({ view = 'committed' }), 2)     -- b とその返信
    T.eq(#comments.list({ view = 'uncommitted' }), 3)   -- a, c, legacy
    T.eq(#comments.list({ view = 'all' }), 3)           -- 'all' は uncommitted のエイリアス
    T.eq(#comments.threads({ view = 'committed' }), 1)
    -- view 指定つき clear はそのバケットだけ消す
    comments.clear({ view = 'committed' })
    T.eq(#comments.list({ view = 'committed' }), 0)
    T.eq(#comments.list({ view = 'uncommitted' }), 3)
  end)

  T.it('removes a top-level comment together with its replies', function()
    comments.reset()
    local top = comments.add({ file = 'a.txt', new_line = 1, body = 'root' })
    comments.reply({ parent_id = top.id, body = 'r1' })
    comments.add({ file = 'a.txt', new_line = 2, body = 'keep' })
    T.ok(comments.remove(top.id))
    T.eq(#comments.list(), 1)
    T.eq(comments.list()[1].body, 'keep')
    T.ok(comments.remove('missing') == false)
  end)

  T.it('clears everything or by filter', function()
    comments.reset()
    comments.add({ file = 'a.txt', new_line = 1, body = 'a' })
    comments.add({ file = 'b.txt', new_line = 1, body = 'b' })
    comments.clear({ file = 'a.txt' })
    T.eq(#comments.list(), 1)
    comments.clear()
    T.eq(#comments.list(), 0)
  end)
end)

T.summary()
