local T = dofile(TESTS_DIR .. '/helpers.lua')
local path = require('config.path_completion')

T.describe('path_completion.path_fragment', function()
  T.it('detects relative / absolute / home path fragments', function()
    T.eq(path.path_fragment('x = "./src/fo'), './src/fo')
    T.eq(path.path_fragment('import "../lib/'), '../lib/')
    T.eq(path.path_fragment('f("~/dot/con'), '~/dot/con')
    T.eq(path.path_fragment('open /usr/lo'), '/usr/lo')
    T.eq(path.path_fragment('  ./'), './')
  end)

  T.it('rejects normal words and method-like dots', function()
    T.eq(path.path_fragment('local foo'), nil)
    T.eq(path.path_fragment('vim.'), nil)
    T.eq(path.path_fragment('obj.method'), nil)
    T.eq(path.path_fragment(''), nil)
    T.eq(path.path_fragment('foo('), nil)
  end)
end)

T.describe('path_completion.parse', function()
  T.it('splits dir and prefix, resolves relative to base', function()
    local dir = vim.fn.tempname()
    vim.fn.mkdir(dir .. '/src/components', 'p')
    local ctx = path.parse('img "./src/com', dir)
    T.ok(ctx ~= nil, 'should parse')
    T.eq(ctx.prefix, 'com')
    T.eq(ctx.dir, vim.fn.fnamemodify(dir .. '/src', ':p'))
    T.eq(ctx.start_col, #'img "./src/' + 1)
  end)

  T.it('returns nil when the directory does not exist', function()
    T.eq(path.parse('"./no/such/dir/x', '/tmp'), nil)
  end)

  T.it('empty prefix when fragment ends with slash', function()
    local dir = vim.fn.tempname()
    vim.fn.mkdir(dir .. '/src', 'p')
    local ctx = path.parse('"./src/', dir)
    T.ok(ctx ~= nil)
    T.eq(ctx.prefix, '')
    T.eq(ctx.dir, vim.fn.fnamemodify(dir .. '/src', ':p'))
  end)
end)

T.describe('path_completion.list', function()
  T.it('lists files and dirs, dirs first, with trailing slash on dirs', function()
    local dir = vim.fn.tempname()
    vim.fn.mkdir(dir .. '/alpha', 'p')
    T.write_file(dir .. '/beta.txt', { 'x' })
    T.write_file(dir .. '/gamma.txt', { 'y' })

    local items = path.list(dir, '')
    local words = vim.tbl_map(function(i) return i.word end, items)
    T.eq(words[1], 'alpha/')
    T.ok(vim.tbl_contains(words, 'beta.txt'))
    T.ok(vim.tbl_contains(words, 'gamma.txt'))
    T.eq(items[1].kind, 'Folder')
    T.rmrf(dir)
  end)

  T.it('filters by prefix (case-insensitive)', function()
    local dir = vim.fn.tempname()
    vim.fn.mkdir(dir, 'p')
    T.write_file(dir .. '/Foo.ts', { 'a' })
    T.write_file(dir .. '/bar.ts', { 'b' })
    local items = path.list(dir, 'fo')
    T.eq(#items, 1)
    T.eq(items[1].word, 'Foo.ts')
    T.rmrf(dir)
  end)

  T.it('hides dotfiles by default', function()
    local dir = vim.fn.tempname()
    vim.fn.mkdir(dir, 'p')
    T.write_file(dir .. '/visible.txt', { 'a' })
    T.write_file(dir .. '/.hidden', { 'b' })
    local items = path.list(dir, '')
    local words = vim.tbl_map(function(i) return i.word end, items)
    T.ok(vim.tbl_contains(words, 'visible.txt'))
    T.ok(not vim.tbl_contains(words, '.hidden'))
    local with_hidden = path.list(dir, '', { show_hidden = true })
    local hw = vim.tbl_map(function(i) return i.word end, with_hidden)
    T.ok(vim.tbl_contains(hw, '.hidden'))
    T.rmrf(dir)
  end)

  T.it('reveals dotfiles when the prefix starts with a dot', function()
    local dir = vim.fn.tempname()
    vim.fn.mkdir(dir .. '/.github', 'p')
    T.write_file(dir .. '/.gitignore', { 'a' })
    T.write_file(dir .. '/.env', { 'b' })
    local items = path.list(dir, '.git')
    local words = vim.tbl_map(function(i) return i.word end, items)
    T.eq(#items, 2)
    T.ok(vim.tbl_contains(words, '.github/'))
    T.ok(vim.tbl_contains(words, '.gitignore'))
    T.ok(not vim.tbl_contains(words, '.env'))
    T.rmrf(dir)
  end)
end)

T.describe('path_completion.is_path_context', function()
  T.it('true only when parse succeeds against an existing dir', function()
    local dir = vim.fn.tempname()
    vim.fn.mkdir(dir .. '/src', 'p')
    -- parse uses base_dir() from current buffer by default; pass via parse for isolation
    T.ok(path.parse('"./src/', dir) ~= nil)
    T.eq(path.parse('local foo', dir), nil)
    T.rmrf(dir)
  end)
end)

T.describe('path_completion.resolve_dir', function()
  T.it('resolves relative, absolute, and empty dir_part', function()
    local base = vim.fn.tempname()
    vim.fn.mkdir(base .. '/sub', 'p')
    T.eq(path.resolve_dir('', base), vim.fn.fnamemodify(base, ':p'))
    T.eq(path.resolve_dir('sub', base), vim.fn.fnamemodify(base .. '/sub', ':p'))
    T.eq(path.resolve_dir('sub/', base), vim.fn.fnamemodify(base .. '/sub', ':p'))
    T.eq(path.resolve_dir('/tmp', base), vim.fn.fnamemodify('/tmp', ':p'))
    T.eq(path.resolve_dir('missing', base), nil)
    T.rmrf(base)
  end)

  T.it('collapses ./ and ../ without resolving symlinks in the path', function()
    local base = vim.fn.tempname()
    vim.fn.mkdir(base .. '/sub/deep', 'p')
    local plain = vim.fn.fnamemodify(base .. '/sub', ':p')
    -- macOS の tempname() は /var（= /private/var への symlink）配下を返す。
    -- `./` `../` の有無で symlink 解決の有無が変わらないこと
    T.eq(path.resolve_dir('./sub', base), plain)
    T.eq(path.resolve_dir('sub/deep/..', base), plain)
    T.eq(path.resolve_dir('./sub/./deep/../', base), plain)
    T.rmrf(base)
  end)
end)

T.summary()
